import { expect, test } from '@playwright/test'

const apiBaseURL = process.env.E2E_API_BASE_URL || 'http://127.0.0.1:8080'
const testPrefix = `${process.env.E2E_TEST_PREFIX || 'CP_E2E'}_${Date.now()}`

function credentials(role) {
  const prefix = role.toUpperCase()
  const username = process.env[`E2E_${prefix}_USERNAME`]
  const password = process.env[`E2E_${prefix}_PASSWORD`]
  if (!username || !password) {
    throw new Error(`Missing E2E_${prefix}_USERNAME or E2E_${prefix}_PASSWORD`)
  }
  return { username, password }
}

async function apiOk(request, method, path, options = {}) {
  const response = await request.fetch(`${apiBaseURL}${path}`, {
    method,
    ...options
  })
  expect(response.ok(), `${method} ${path}`).toBeTruthy()
  const payload = await response.json()
  expect(payload.code, `${method} ${path} business code`).toBe(200)
  return payload.data
}

async function login(request, role) {
  const { username, password } = credentials(role)
  const captcha = await apiOk(request, 'GET', '/api/auth/captcha')
  return apiOk(request, 'POST', '/api/auth/login', {
    data: {
      username,
      password,
      captchaKey: captcha.captchaKey,
      captchaCode: captcha.captchaText
    }
  })
}

async function seedSession(page, session) {
  await page.addInitScript(({ token, user }) => {
    window.localStorage.setItem('token', token)
    window.localStorage.setItem('user', JSON.stringify(user))
  }, session)
}

function watchConsole(page) {
  const messages = []
  page.on('console', (message) => {
    if (['error', 'warning'].includes(message.type())) {
      messages.push(`${message.type()}: ${message.text()}`)
    }
  })
  page.on('pageerror', (error) => {
    messages.push(`pageerror: ${error.message}`)
  })
  return messages
}

async function silenceBrowserDefaultRequests(page) {
  await page.route('**/favicon.ico', (route) => route.fulfill({ status: 204, body: '' }))
}

function activityPayload(title, started = false) {
  const now = new Date()
  const start = started
    ? new Date(now.getTime() - 60 * 60 * 1000)
    : new Date(now.getTime() + 7 * 24 * 60 * 60 * 1000)
  const end = started
    ? new Date(now.getTime() + 60 * 60 * 1000)
    : new Date(start.getTime() + 2 * 60 * 60 * 1000)
  const deadline = new Date(start.getTime() - 2 * 60 * 60 * 1000)
  return {
    title,
    category: 'Other',
    tags: ['e2e', 'smoke'],
    startTime: start.toISOString().slice(0, 19),
    endTime: end.toISOString().slice(0, 19),
    signupDeadline: deadline.toISOString().slice(0, 19),
    city: 'Beijing',
    address: 'E2E Test Address',
    longitude: 116.4,
    latitude: 39.9,
    minParticipants: 1,
    maxParticipants: 3,
    costType: 'FREE',
    costAmount: 0,
    aaRule: 'E2E test data',
    coverUrl: '',
    description: `${title} generated by Playwright smoke test.`,
    notes: 'Generated test data with a cleanup prefix.',
    needApproval: false
  }
}

test('login, activity list, detail, publish, edit, cancel and finish flow', async ({ page, request }) => {
  const consoleMessages = watchConsole(page)
  await silenceBrowserDefaultRequests(page)
  const session = await login(request, 'user')
  await seedSession(page, session)

  await page.goto('/')
  await expect(page.locator('.activity-card').first()).toBeVisible()
  await page.locator('.activity-card').first().click()
  await expect(page).toHaveURL(/\/activities\/\d+/)

  const cancelTitle = `${testPrefix}_cancel`
  const created = await apiOk(request, 'POST', '/api/activities', {
    headers: { Authorization: `Bearer ${session.token}` },
    data: activityPayload(cancelTitle)
  })
  await page.goto(`/activities/${created.id}`)
  await expect(page.getByRole('heading', { name: cancelTitle })).toBeVisible()

  const editedTitle = `${cancelTitle}_edited`
  await apiOk(request, 'PUT', `/api/activities/${created.id}`, {
    headers: { Authorization: `Bearer ${session.token}` },
    data: activityPayload(editedTitle)
  })
  await page.goto(`/publish?editId=${created.id}`)
  await expect(page.locator('input').first()).toHaveValue(editedTitle)
  await apiOk(request, 'PATCH', `/api/activities/${created.id}/cancel`, {
    headers: { Authorization: `Bearer ${session.token}` }
  })
  const cancelled = await apiOk(request, 'GET', `/api/activities/${created.id}`)
  expect(cancelled.status).toBe('CANCELLED')

  const finishTitle = `${testPrefix}_finish`
  const started = await apiOk(request, 'POST', '/api/activities', {
    headers: { Authorization: `Bearer ${session.token}` },
    data: activityPayload(finishTitle, true)
  })
  await apiOk(request, 'PATCH', `/api/activities/${started.id}/finish`, {
    headers: { Authorization: `Bearer ${session.token}` }
  })
  const finished = await apiOk(request, 'GET', `/api/activities/${started.id}`)
  expect(finished.status).toBe('FINISHED')
  expect(consoleMessages).toEqual([])
})

test('admin dashboard, analytics ranges and user route guard', async ({ page, request }) => {
  const consoleMessages = watchConsole(page)
  await silenceBrowserDefaultRequests(page)
  const adminSession = await login(request, 'admin')
  await seedSession(page, adminSession)

  await page.goto('/admin/dashboard')
  await expect(page).toHaveURL(/\/admin\/dashboard/)
  await expect(page.locator('canvas').first()).toBeVisible()
  await expect(page.locator('.el-table, table').first()).toBeVisible()

  await page.goto('/admin/analytics')
  await expect(page).toHaveURL(/\/admin\/analytics/)
  await expect.poll(async () => page.locator('canvas').count()).toBeGreaterThanOrEqual(8)

  await page.locator('label:has(input[value="LAST_90_DAYS"])').click()
  await expect(page.locator('.analytics-range')).toContainText('2026')
  await page.locator('label:has(input[value="THIS_YEAR"])').click()
  await expect(page.locator('.analytics-range')).toContainText('2026-01-01')
  await page.locator('label:has(input[value="CUSTOM"])').click()
  const dateInputs = page.locator('.el-date-editor input')
  await dateInputs.nth(0).fill('2026-04-01')
  await dateInputs.nth(1).fill('2026-07-12')
  await page.keyboard.press('Enter')
  await expect(page.locator('.analytics-range')).toContainText('2026-04-01')

  const userSession = await login(request, 'user')
  const userPage = await page.context().newPage()
  const userConsoleMessages = watchConsole(userPage)
  await silenceBrowserDefaultRequests(userPage)
  await seedSession(userPage, userSession)
  await userPage.goto('/admin/dashboard')
  await expect(userPage).not.toHaveURL(/\/admin\/dashboard/)
  expect(userConsoleMessages).toEqual([])
  await userPage.close()
  expect(consoleMessages).toEqual([])
})
