import { expect, test } from '@playwright/test'

const apiBaseURL = process.env.E2E_API_BASE_URL || 'http://127.0.0.1:8080'
const testPrefix = `${process.env.E2E_TEST_PREFIX || 'CP_E2E'}_${Date.now()}`

function credentials(role) {
  const prefix = role.toUpperCase()
  const username = process.env[`E2E_${prefix}_USERNAME`]
  const password = process.env[`E2E_${prefix}_PASSWORD`]
  if (!username || !password) {
    throw new Error(`Missing E2E_${prefix}_USERNAME or E2E_${prefix}_PASSWORD`)
  }
  return { username, password }
}

async function apiOk(request, method, path, options = {}) {
  const response = await request.fetch(`${apiBaseURL}${path}`, {
    method,
    ...options
  })
  expect(response.ok(), `${method} ${path}`).toBeTruthy()
  const payload = await response.json()
  expect(payload.code, `${method} ${path} business code`).toBe(200)
  return payload.data
}

async function login(request, role) {
  const { username, password } = credentials(role)
  const captcha = await apiOk(request, 'GET', '/api/auth/captcha')
  return apiOk(request, 'POST', '/api/auth/login', {
    data: {
      username,
      password,
      captchaKey: captcha.captchaKey,
      captchaCode: captcha.captchaText
    }
  })
}

async function seedSession(page, session) {
  await page.addInitScript(({ token, user }) => {
    window.localStorage.setItem('token', token)
    window.localStorage.setItem('user', JSON.stringify(user))
  }, session)
}

function watchConsole(page) {
  const messages = []
  page.on('console', (message) => {
    if (['error', 'warning'].includes(message.type())) {
      messages.push(`${message.type()}: ${message.text()}`)
    }
  })
  page.on('pageerror', (error) => {
    messages.push(`pageerror: ${error.message}`)
  })
  return messages
}

async function silenceBrowserDefaultRequests(page) {
  await page.route('**/favicon.ico', (route) => route.fulfill({ status: 204, body: '' }))
}

async function mockMobileNavigationApis(page) {
  await page.route(/^https?:\/\/[^/]+\/api\//, (route) => {
    const pathname = new URL(route.request().url()).pathname
    let data = { records: [], total: 0 }

    if (pathname === '/api/notices/unread-count') {
      data = 0
    } else if (pathname === '/api/user/profile-overview') {
      data = {
        username: 'navigation_user',
        nickname: 'Navigation User',
        city: 'Beijing',
        creditScore: 100,
        creditLevel: 'GOOD',
        publishedActivityCount: 0,
        joinedActivityCount: 0,
        waitingActivityCount: 0,
        receivedReviewCount: 0,
        averageRating: 0,
        unreadNoticeCount: 0,
        interestTags: []
      }
    }

    return route.fulfill({
      status: 200,
      contentType: 'application/json',
      body: JSON.stringify({ code: 200, data })
    })
  })
}

function activityPayload(title, started = false) {
  const now = new Date()
  const start = started
    ? new Date(now.getTime() - 60 * 60 * 1000)
    : new Date(now.getTime() + 7 * 24 * 60 * 60 * 1000)
  const end = started
    ? new Date(now.getTime() + 60 * 60 * 1000)
    : new Date(start.getTime() + 2 * 60 * 60 * 1000)
  const deadline = new Date(start.getTime() - 2 * 60 * 60 * 1000)
  return {
    title,
    category: 'Other',
    tags: ['e2e', 'smoke'],
    startTime: start.toISOString().slice(0, 19),
    endTime: end.toISOString().slice(0, 19),
    signupDeadline: deadline.toISOString().slice(0, 19),
    city: 'Beijing',
    address: 'E2E Test Address',
    longitude: 116.4,
    latitude: 39.9,
    minParticipants: 1,
    maxParticipants: 3,
    costType: 'FREE',
    costAmount: 0,
    aaRule: 'E2E test data',
    coverUrl: '',
    description: `${title} generated by Playwright smoke test.`,
    notes: 'Generated test data with a cleanup prefix.',
    needApproval: false
  }
}

test('login, activity list, detail, publish, edit, cancel and finish flow', async ({ page, request }) => {
  const consoleMessages = watchConsole(page)
  await silenceBrowserDefaultRequests(page)
  const session = await login(request, 'user')
  await seedSession(page, session)

  await page.goto('/')
  await expect(page.locator('.activity-card').first()).toBeVisible()
  await page.locator('.activity-card').first().click()
  await expect(page).toHaveURL(/\/activities\/\d+/)

  const cancelTitle = `${testPrefix}_cancel`
  const created = await apiOk(request, 'POST', '/api/activities', {
    headers: { Authorization: `Bearer ${session.token}` },
    data: activityPayload(cancelTitle)
  })
  await page.goto(`/activities/${created.id}`)
  await expect(page.getByRole('heading', { name: cancelTitle })).toBeVisible()

  const editedTitle = `${cancelTitle}_edited`
  await apiOk(request, 'PUT', `/api/activities/${created.id}`, {
    headers: { Authorization: `Bearer ${session.token}` },
    data: activityPayload(editedTitle)
  })
  await page.goto(`/publish?editId=${created.id}`)
  await expect(page.locator('input').first()).toHaveValue(editedTitle)
  await apiOk(request, 'PATCH', `/api/activities/${created.id}/cancel`, {
    headers: { Authorization: `Bearer ${session.token}` }
  })
  const cancelled = await apiOk(request, 'GET', `/api/activities/${created.id}`)
  expect(cancelled.status).toBe('CANCELLED')

  const finishTitle = `${testPrefix}_finish`
  const started = await apiOk(request, 'POST', '/api/activities', {
    headers: { Authorization: `Bearer ${session.token}` },
    data: activityPayload(finishTitle, true)
  })
  await apiOk(request, 'PATCH', `/api/activities/${started.id}/finish`, {
    headers: { Authorization: `Bearer ${session.token}` }
  })
  const finished = await apiOk(request, 'GET', `/api/activities/${started.id}`)
  expect(finished.status).toBe('FINISHED')
  expect(consoleMessages).toEqual([])
})

test('mobile tabbar navigation and active state follow current route', async ({ page }) => {
  await silenceBrowserDefaultRequests(page)
  await mockMobileNavigationApis(page)
  await seedSession(page, {
    token: 'e2e-navigation-token',
    user: {
      id: 1,
      username: 'navigation_user',
      nickname: 'Navigation User',
      role: 'USER',
      city: 'Beijing'
    }
  })

  const tabbar = page.locator('.van-tabbar')
  const tabs = [
    { label: '首页', path: '/' },
    { label: '地图', path: '/map' },
    { label: '发布', path: '/publish' },
    { label: '报名', path: '/my-signups' },
    { label: '我的', path: '/profile' }
  ]

  const expectPath = async (path) => {
    await expect.poll(() => new URL(page.url()).pathname).toBe(path)
  }
  const getTab = (label) => tabbar.locator('[role="tab"]', { hasText: label })
  const expectOnlyActiveTab = async (label) => {
    const activeTabs = tabbar.locator('[role="tab"][aria-selected="true"]')
    await expect(activeTabs).toHaveCount(1)
    await expect(getTab(label)).toHaveAttribute('aria-selected', 'true')
  }

  for (const tab of tabs) {
    await page.goto(tab.path)
    await expectPath(tab.path)
    await expectOnlyActiveTab(tab.label)
  }

  for (const tab of tabs.slice(1)) {
    await page.goto(tab.path)
    await getTab('首页').click()
    await expectPath('/')
    await expectOnlyActiveTab('首页')
  }

  await page.goto('/')
  for (const tab of tabs.slice(1)) {
    await getTab(tab.label).click()
    await expectPath(tab.path)
    await expectOnlyActiveTab(tab.label)
  }

  await getTab('首页').click()
  await expectPath('/')
  await expectOnlyActiveTab('首页')

  await page.goBack()
  await expectPath('/profile')
  await expectOnlyActiveTab('我的')

  await page.goForward()
  await expectPath('/')
  await expectOnlyActiveTab('首页')

  await page.reload()
  await expectPath('/')
  await expectOnlyActiveTab('首页')

  await getTab('首页').click()
  await expectPath('/')
  await expectOnlyActiveTab('首页')
})

test('guest home keeps the original activity flow without requesting recommendations', async ({ page }) => {
  await silenceBrowserDefaultRequests(page)
  let recommendationRequests = 0

  await page.route(/^https?:\/\/[^/]+\/api\//, async (route) => {
    const pathname = new URL(route.request().url()).pathname
    if (pathname === '/api/recommendations/activities') {
      recommendationRequests += 1
    }

    await route.fulfill({
      status: 200,
      contentType: 'application/json',
      body: JSON.stringify({ code: 200, data: { records: [], total: 0 } })
    })
  })

  await page.goto('/')
  await expect(page.getByText('活动发现', { exact: true })).toBeVisible()
  await expect(page.getByText('为你推荐', { exact: true })).toHaveCount(0)
  expect(recommendationRequests).toBe(0)
})

test('logged-in home shows explainable recommendations and opens activity detail', async ({ page }) => {
  await silenceBrowserDefaultRequests(page)
  await page.addInitScript(() => {
    window.WebSocket = class MockWebSocket {
      static CONNECTING = 0
      static OPEN = 1
      static CLOSED = 3

      constructor() {
        this.readyState = MockWebSocket.OPEN
        queueMicrotask(() => this.onopen?.())
      }

      send() {}

      close() {
        this.readyState = MockWebSocket.CLOSED
        this.onclose?.()
      }
    }

    Object.defineProperty(navigator, 'geolocation', {
      configurable: true,
      value: {
        getCurrentPosition(_success, error) {
          error({ code: 1, message: 'Permission denied by E2E test' })
        }
      }
    })
  })
  const recommendedActivity = {
    id: 901,
    creatorId: 88,
    title: '周末新手桌游局',
    category: '桌游',
    tags: ['周末', '新手友好'],
    startTime: '2026-09-05T14:00:00',
    endTime: '2026-09-05T17:00:00',
    signupDeadline: '2026-09-04T20:00:00',
    city: '北京',
    address: '朝阳区桌游店',
    longitude: 116.4,
    latitude: 39.9,
    minParticipants: 2,
    maxParticipants: 8,
    approvedCount: 3,
    favoriteCount: 4,
    waitlistCount: 0,
    costType: 'AA',
    costAmount: 45,
    status: 'SIGNING',
    creator: { id: 88, nickname: '桌游发起人', avatarUrl: null, creditScore: 108 }
  }

  await page.route(/^https?:\/\/[^/]+\/api\//, async (route) => {
    const pathname = new URL(route.request().url()).pathname
    let data = { records: [], total: 0 }
    if (pathname === '/api/recommendations/activities') {
      data = [{
        activity: recommendedActivity,
        recommendationScore: 92.35,
        distanceKm: null,
        reasons: ['匹配你的兴趣：周末、新手友好', '近期报名热度较高', '发起人信用良好'],
        scoreDetail: { interest: 100, distance: null, hotness: 72, time: 88, credit: 96 }
      }]
    } else if (pathname === '/api/activities/901') {
      data = recommendedActivity
    } else if (pathname === '/api/notices/unread-count') {
      data = 0
    }
    await route.fulfill({
      status: 200,
      contentType: 'application/json',
      body: JSON.stringify({ code: 200, data })
    })
  })
  await seedSession(page, {
    token: 'recommendation-feature-token',
    user: { id: 7, username: 'recommendation_user', nickname: '推荐用户', role: 'USER' }
  })

  await page.goto('/')
  await expect(page.getByText('为你推荐', { exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: '使用位置优化' })).toBeVisible()
  await expect(page.getByText(recommendedActivity.title)).toBeVisible()
  await expect(page.getByText('匹配你的兴趣：周末、新手友好')).toBeVisible()

  await page.getByPlaceholder('搜索活动、地点、说明').fill('飞盘')
  await page.getByPlaceholder('搜索活动、地点、说明').press('Enter')
  await expect(page.getByText(recommendedActivity.title)).toBeVisible()
  await page.getByText('运动', { exact: true }).first().click()
  await expect(page.getByText(recommendedActivity.title)).toBeVisible()

  await page.getByRole('button', { name: '使用位置优化' }).click()
  await expect(page.locator('.van-toast')).toContainText('未能获取位置，已保留当前推荐')
  await expect(page.getByText(recommendedActivity.title)).toBeVisible()

  await page.locator('.recommendation-item .activity-card').click()
  await expect(page).toHaveURL('/activities/901')
})

test('admin dashboard, analytics ranges and user route guard', async ({ page, request }) => {
  const consoleMessages = watchConsole(page)
  await silenceBrowserDefaultRequests(page)
  const adminSession = await login(request, 'admin')
  await seedSession(page, adminSession)

  await page.goto('/admin/dashboard')
  await expect(page).toHaveURL(/\/admin\/dashboard/)
  await expect(page.locator('canvas').first()).toBeVisible()
  await expect(page.locator('.el-table, table').first()).toBeVisible()

  await page.goto('/admin/analytics')
  await expect(page).toHaveURL(/\/admin\/analytics/)
  await expect.poll(async () => page.locator('canvas').count()).toBeGreaterThanOrEqual(8)

  await page.locator('label:has(input[value="LAST_90_DAYS"])').click()
  await expect(page.locator('.analytics-range')).toContainText('2026')
  await page.locator('label:has(input[value="THIS_YEAR"])').click()
  await expect(page.locator('.analytics-range')).toContainText('2026-01-01')
  await page.locator('label:has(input[value="CUSTOM"])').click()
  const dateInputs = page.locator('.el-date-editor input')
  await dateInputs.nth(0).fill('2026-04-01')
  await dateInputs.nth(1).fill('2026-07-12')
  await page.keyboard.press('Enter')
  await expect(page.locator('.analytics-range')).toContainText('2026-04-01')

  const userSession = await login(request, 'user')
  const userPage = await page.context().newPage()
  const userConsoleMessages = watchConsole(userPage)
  await silenceBrowserDefaultRequests(userPage)
  await seedSession(userPage, userSession)
  await userPage.goto('/admin/dashboard')
  await expect(userPage).not.toHaveURL(/\/admin\/dashboard/)
  expect(userConsoleMessages).toEqual([])
  await userPage.close()
  expect(consoleMessages).toEqual([])
})

test('image cropper submits and removes activity covers and profile avatars', async ({ page }) => {
  await silenceBrowserDefaultRequests(page)
  const activityRequests = []
  const profileRequests = []
  let profileFailuresRemaining = 1
  let currentAvatar = null
  const activity = {
    id: 501,
    creatorId: 1,
    title: 'Image Cropper Activity',
    category: '观影',
    tags: ['图片测试'],
    startTime: '2026-08-01T19:00:00',
    endTime: '2026-08-01T22:00:00',
    signupDeadline: '2026-08-01T12:00:00',
    city: '北京',
    address: '图片测试地点',
    longitude: 116.4,
    latitude: 39.9,
    minParticipants: 2,
    maxParticipants: 6,
    costType: 'FREE',
    costAmount: 0,
    aaRule: '',
    coverUrl: '/uploads/activity/existing.jpg',
    description: '图片裁剪端到端测试',
    notes: '',
    needApproval: false,
    approvedCount: 0,
    status: 'SIGNING',
    creator: { id: 1, nickname: 'Image User', avatarUrl: null }
  }

  await page.route(/^https?:\/\/[^/]+\/api\//, async (route) => {
    const request = route.request()
    const pathname = new URL(request.url()).pathname
    const method = request.method()
    let data = { records: [], total: 0 }

    if (pathname === '/api/notices/unread-count') {
      data = 0
    } else if (pathname === '/api/activities' && method === 'POST') {
      activityRequests.push(request.postDataBuffer())
      data = { ...activity, coverUrl: '/uploads/activity/new-cover.jpg' }
    } else if (pathname === '/api/activities/501' && method === 'PUT') {
      activityRequests.push(request.postDataBuffer())
      data = { ...activity, coverUrl: null }
    } else if (pathname === '/api/activities/501') {
      data = activity
    } else if (pathname === '/api/user/profile' && method === 'PUT') {
      profileRequests.push(request.postDataBuffer())
      if (profileFailuresRemaining > 0) {
        profileFailuresRemaining -= 1
        await route.fulfill({
          status: 500,
          contentType: 'application/json',
          body: JSON.stringify({ code: 500, message: 'mock profile save failure', data: null })
        })
        return
      }
      const body = request.postDataBuffer()?.toString('latin1') || ''
      currentAvatar = body.includes('removeAvatar') ? null : '/uploads/avatar/new-avatar.jpg'
      data = userData(currentAvatar)
    } else if (pathname === '/api/user/me') {
      data = userData(currentAvatar)
    }

    await route.fulfill({
      status: 200,
      contentType: 'application/json',
      body: JSON.stringify({ code: 200, data })
    })
  })

  await seedSession(page, {
    token: 'image-feature-token',
    user: userData(null)
  })

  await page.goto('/publish')
  await page.locator('.van-field', { hasText: '标题' }).locator('input').fill(activity.title)
  await page.locator('.van-field', { hasText: '地址' }).locator('input').fill(activity.address)
  await page.locator('.van-field', { hasText: '说明' }).locator('textarea').fill(activity.description)
  await page.locator('input[type="file"]').setInputFiles({
    name: 'unsupported.gif',
    mimeType: 'image/gif',
    buffer: Buffer.from('GIF89a')
  })
  await expect(page.locator('.van-toast')).toContainText('仅支持 JPG、PNG、WebP')
  await page.locator('input[type="file"]').setInputFiles({
    name: 'too-large.png',
    mimeType: 'image/png',
    buffer: Buffer.alloc(10 * 1024 * 1024 + 1)
  })
  await expect(page.locator('.van-toast')).toContainText('原图不能超过 10MB')
  await page.locator('input[type="file"]').setInputFiles(testPngFile('cover.png'))
  await expect(page.locator('cropper-selection')).toBeVisible()
  await page.locator('.van-nav-bar__right').getByText('确定', { exact: true }).click()
  await expect(page.locator('.activity-cover-preview')).toHaveAttribute('src', /^blob:/)
  const firstCoverPreview = await page.locator('.activity-cover-preview').getAttribute('src')
  await page.locator('input[type="file"]').setInputFiles(testPngFile('replacement-cover.png'))
  await expect(page.locator('cropper-selection')).toBeVisible()
  await page.locator('.van-nav-bar__left').getByText('取消', { exact: true }).click()
  await expect(page.locator('.activity-cover-preview')).toHaveAttribute('src', firstCoverPreview)
  await page.locator('input[type="file"]').setInputFiles(testPngFile('replacement-cover.png'))
  await expect(page.locator('cropper-selection')).toBeVisible()
  await page.locator('.van-nav-bar__right').getByText('确定', { exact: true }).click()
  await expect.poll(() => page.locator('.activity-cover-preview').getAttribute('src')).not.toBe(firstCoverPreview)
  await page.locator('form .van-button--block').click()
  await expect.poll(() => activityRequests.length).toBe(1)
  const createBody = activityRequests[0].toString('latin1')
  expect(createBody).toContain('activity-cover.jpg')
  expect(createBody).toContain('Image Cropper Activity')

  await page.goto('/publish?editId=501')
  await expect(page.locator('.activity-cover-preview')).toHaveAttribute('src', activity.coverUrl)
  await page.getByRole('button', { name: '删除图片' }).click()
  await page.locator('form .van-button--block').click()
  await expect.poll(() => activityRequests.length).toBe(2)
  expect(activityRequests[1].toString('latin1')).toContain('removeCover')

  await page.goto('/profile/edit')
  await page.locator('input[type="file"]').setInputFiles(testPngFile('avatar.png'))
  await expect(page.locator('cropper-selection')).toBeVisible()
  await page.locator('.van-nav-bar__right').getByText('确定', { exact: true }).click()
  await expect(page.locator('.avatar-editor-preview')).toHaveAttribute('src', /^blob:/)
  await page.locator('form .van-button--block').click()
  await expect.poll(() => profileRequests.length).toBe(1)
  expect(profileRequests[0].toString('latin1')).toContain('avatar.jpg')
  await expect(page.locator('.avatar-editor-preview')).toHaveAttribute('src', /^blob:/)
  await page.locator('form .van-button--block').click()
  await expect.poll(() => profileRequests.length).toBe(2)
  expect(profileRequests[1].toString('latin1')).toContain('avatar.jpg')

  await page.getByRole('button', { name: '删除头像' }).click()
  await page.locator('form .van-button--block').click()
  await expect.poll(() => profileRequests.length).toBe(3)
  expect(profileRequests[2].toString('latin1')).toContain('removeAvatar')
})

function userData(avatarUrl) {
  return {
    id: 1,
    username: 'image_user',
    nickname: 'Image User',
    role: 'USER',
    city: '北京',
    bio: 'Image feature test user',
    interestTags: [],
    avatarUrl
  }
}

function testPngFile(name) {
  return {
    name,
    mimeType: 'image/png',
    buffer: Buffer.from(
      'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=',
      'base64'
    )
  }
}
